environment:
    matrix:
        - PYTHON: Python27
        - PYTHON: Python34
        - PYTHON: Python35

install:
    - C:\%PYTHON%\Scripts\pip install networkx pydotplus PyYAML PyKwalify pytest

build: off

test_script:
    - C:\%PYTHON%\Scripts\pytest
