language: python
python:
    - 2.7
    - 3.4
    - 3.5
    - pypy
    - pypy3

os: linux

matrix:
    include:
        - os: osx
          language: generic

install:
    - if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
        pip install pytest;
      elif [[ "${TRAVIS_PYTHON_VERSION}" == "2.7" ]]; then
        export RUN_COVERAGE=true;
        pip install coverage codecov pytest-cov;
      fi &&
      pip install networkx pydotplus PyYAML PyKwalify

script:
    - if [[ $RUN_COVERAGE == true ]]; then
        py.test --cov=cppdep --cov=graph --cov-config .coveragerc && codecov;
      else
        py.test;
      fi
