internal:  # A list of package groups for analysis.
    - name: Awesome  # The name of a package-group.
      path: /path/to/awesome/project  # The root path for the packages in the group.
      packages:  # A list of member packages.
        - name: Core
          src: src
          ignore:
              - src/main.cc
              - src/utility
        - name: GUI
          src: gui
        - name: Trash
          src: src/utility/*.h  # The source paths are glob patterns.

external:  # External package groups (not analyzed but searched for headers/components).
    - name: System
      path: /usr/include
      packages:
          - name: SystemInclude
            include: .  # The relative-to-group-root path to search for headers.
          - name: STL
            include: c++/5
          - name: Boost
            alias: boost  # An alias path to map header files to the package.
            pattern: boost  # The regex.match pattern for include directives.
